apiVersion: apps/v1
kind: Service
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: <your-registry>/<your-app-name>:<tag>
        ports:
        - containerPort: 80
